default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: askit
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: askit_test

development:
  <<: *default
  database: askit_development
